# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Publish a Docker image

on:
  push:
    branches: ['main']

env:
#  REGISTRY: ghcr.io
  IMAGE_NAME: taskyfabrizia

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}
  
#      - name: Azure ACR Login
#        uses: azure/docker-login@v1
#        with:
#          login-server: ${{ secrets.ACR_NAME }}
#          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
#          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest


#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#        with:
#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#          flavor: |
#            latest=true

#      - name: Build and push Docker image
#        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
