apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky-fabwizia
  template:
    metadata:
      labels:
        app: tasky-fabwizia
    spec:
      containers:
      - name: tasky-fabwizia
        image: fabwiziaregistry.azurecr.io/fabriziav/tasky_fabwizia:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://74.225.169.215:27017/supermarket"
---
apiVersion: v1
kind: Service
metadata:
  name: tasky-fabwizia-service
spec:
  type: LoadBalancer
  selector:
    app: tasky_fabwizia
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
