apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskyfabwizia
  template:
    metadata:
      labels:
        app: taskyfabwizia
    spec:
      containers:
      - name: taskyfabwizia
        image: fabwiziaregistry.azurecr.io/fabriziav/tasky_fabwizia:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "mongodb://192.168.10.4:27017/supermarket"
        - name: SECRET_KEY
          value: "secret123"
---
apiVersion: v1
kind: Service
metadata:
  name: tasky-fabwizia-service
spec:
  type: LoadBalancer
  selector:
    app: taskyfabwizia
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
